version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 15
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - tsc && node ./dist
artifacts:
  files:
    - '**/*'