version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm i -g typescript
      - npm i
  build:
    commands:
      - tsc
artifacts:
  files:
    - 'dist/*.js'
    - 'dist/**/*.js'
    - 'package.json'
    - 'node_modules/**/*'